Place la licence entendu inter-province
CQEN-QDCE/Candy pull request #32
Opened 2022-01-13 18:22 UTC by flihp27

Signed-off-by: flihp27 <philippe.foucault@sct.gouv.qc.ca>

2022-01-13 18:23 UTC, flihp27 commented
I basically simply change the gov Qc licence for the Apache 2.

2022-01-13 19:05 UTC, WadeBarnes requested changes

2022-01-13 19:05 UTC, WadeBarnes commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Missing the Copyright date and owner

2022-01-18 16:06 UTC, WadeBarnes approved these changes

2022-01-19 16:25 UTC, merged